# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      brew tap veracode/tap
      brew install gen-ir
      ls
      pwd
      cd iGoat/
      ls -la
      xcodebuild -help
      xcodebuild -list
      xcodebuild -showsdks
      pwd
      xcodebuild archive -project iGoat.xcodeproj  -configuration Debug -scheme iGoat -destination generic/platform=iOS DEBUG_INFORMATION_FORMAT=dwarf-with-dsym -archivePath iGoat.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO | tee build_log.txt
      ls -la 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script:
      ls -la
      ls -la */*