# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      brew tap veracode/tap
      brew install gen-ir
      ls
      pwd
      cd iGoat/
      ls -la
      xcodebuild -help
      xcodebuild -list
      xcodebuild -showsdks
      pwd
- task: Xcode@5
  inputs:
    actions: 'archive'
    configuration: 'Debug'
    sdk: 'iphoneos16.2'
    xcWorkspacePath: 'iGoat/iGoat.xcodeproj'
    scheme: 'iGoat'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationTypeOption: 'devices'
    destinationDevices: 'Any iOS Device'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -la
      ls -la */*